version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: my_sql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: default
networks:
  default:
    name: my_sql
